### ISSUE TITLE
Staline only shows a gray line

### ISSUE THREAD

**Issue by mrLuisFer** [tamton-aquib/staline.nvim#11]
I installed this plugin using Vim Plug but when opening neovim it only shows a gray line
But when I open Treelua it shows up without any color
Neovim v0.6.0-dev

Default:
![error](https://user-images.githubusercontent.com/65029792/134366938-1c9e2cb1-a469-47ac-a5ac-32be4a3f1b85.png)

When treelua opens:
![when open treelua](https://user-images.githubusercontent.com/65029792/134366948-62510ade-f1ac-4beb-9527-59355fef6ed2.png)

**Comment by tamton-aquib** [comment]
Heyyo @mrLuisFer , 
I just tried out your [nvim-dotfiles](https://github.com/mrLuisFer/neovim-dotfiles).

This is how it shows for me:
![image](https://user-images.githubusercontent.com/77913442/134375432-7f14fbc7-07c4-4585-92cc-beb1613ed002.png)

And when i did :NvimTreeToggle :
![image](https://user-images.githubusercontent.com/77913442/134375670-1b5a9c42-b137-455b-af42-ffa5f1223173.png)

The grey color indicates that, the window is inactive.

opened init.vim and it looks like:
![image](https://user-images.githubusercontent.com/77913442/134377445-0e97aaba-1ed3-4a39-b816-87e98539914f.png)

**Comment by mrLuisFer** [comment]
Oh yeah yeah, but in my dotfiles I have two branches, the main one which is the one you tested, there it works correctly but in the second I have lsp configured and for some reason it don't show as in the main branch

![branches](https://user-images.githubusercontent.com/65029792/134396265-a0ae2f4d-e448-4217-876f-eefa69f3f6dd.jpg)

**Comment by mrLuisFer** [comment]
Also when I have the focus on a file it only shows me the part to the right, a gray line
![focus on a file](https://user-images.githubusercontent.com/65029792/134396972-7dbd338c-b28f-4b9d-8b7a-955103bbb770.jpg)

**Comment by tamton-aquib** [comment]
Tried out nvim-lsp branch too...
![image](https://user-images.githubusercontent.com/77913442/134457978-6e9ed4fa-d3cf-45e4-aefc-22f55c1e0517.png)

Opening neovim with `nvim`:
![image](https://user-images.githubusercontent.com/77913442/134458020-f15132ea-4f86-41ae-b2dd-4ea4f0325b61.png)

Trying `:NvimTreeToggle`  
![image](https://user-images.githubusercontent.com/77913442/134458061-13945fab-7c74-44d7-b34f-afdb432e693c.png)

Opening init.vim:
![image](https://user-images.githubusercontent.com/77913442/134458229-6aab92df-ba3c-4f16-a477-d580670a92da.png)

Couldn't reproduce the issue.

Could you try `:messages` to see if there are any errors?

**Comment by mrLuisFer** [comment]
I run/execute `:messages`, but it doesn't show me anything
![messages command](https://user-images.githubusercontent.com/65029792/134531289-dbf94b12-a813-46c8-bcfe-1d51edc4a4ba.png)

**Comment by mrLuisFer** [comment]
ok, I wanted to test my configuration in Windows and i think then it is a problem with my OS (Linux - Kde Neon), because in windows it shows correctly

although i don't really understand the problem because in the main branch if it shows correctly 🤔

**Comment by tamton-aquib** [comment]
Hmm.... that's definitely weird 😅
I'm currently on arch linux, and it works.

Have u tried turning off other plugins and check?
I will probably look into it later this week, and sorry for all these silly troubles haha....

**Comment by mrLuisFer** [comment]
Well then it's not a Staline problem
Unfortunately I still don't know why it does not appear correctly but hey, i close the issue
thx :)
