### ISSUE TITLE
Color Line. exceeding indicator

### ISSUE THREAD

**Issue by fedoranvar** [tamton-aquib/staline.nvim#16]
Good day to you!

I have "Color Line setup from WikiExamples:
When i have one window open - it's okay

But when if i have any splits, then i have exceeding-indicator ("<"):
![image](https://user-images.githubusercontent.com/52028706/140391201-ee008d6a-ed42-43a6-ad28-80c34abe4eed.png)
that's because `vim.o.columns` - is showing width of neovim instance, but not for current window

my question is: 
how to get rid of this sign?

**Comment by tamton-aquib** [comment]
Heyyo @fedoranvar , sorry for the late reply 😅 

Actually i completely forgot about splits when tryin out color line, so i always used `vim.o.columns`.
To get width of a single window, we could use `vim.api.nvim_win_get_width` or `vim.fn.winwidth`
Example:

```lua
require("staline").setup {
    sections = {
        left = {
            function()
                return ("▁"):rep(vim.api.nvim_win_get_width(0))
            end
        }, -- change thickness: "_", "▁", "▂", "▃", "▄", "▅", "▆", "▇", "█"
        mid = {},
        right = {}
    },
}
```

**Comment by fedoranvar** [comment]
@tamton-aquib 

yes, that helped!

Thank you!
