### ISSUE TITLE
User Defined Sections Don't Update

### ISSUE THREAD

**Issue by is0n** [tamton-aquib/staline.nvim#20]
When I put my own sections in the `sections` table, those sections won't update, however, the other sections that are defined by the staline do.

Example Config Using [nvim-gps](https://github.com/SmiteshP/nvim-gps):
```lua
local function context()
	if require("nvim-gps").is_available() then
		return require("nvim-gps").get_location()
	end
	return ''
end

-- Configuration
require('staline').setup{
	sections = {
		left  = { '-mode', 'left_sep', 'file_name' }, -- These will update
		mid   = { context() }, -- This will not update
		right = { 'cool_symbol', 'right_sep', '-line_column', '-cwd' } -- These will update
	},
}
```

**Comment by tamton-aquib** [comment]
Instead of passing the function call:
`mid = { context() }`
try passing the function directly:
`mid = { context }`

And just relaized i havent mentioned this in docs.
lemme know if it works 😬

**Comment by is0n** [comment]
> Instead of passing the function call:
mid = { context() }
try passing the function directly:
mid = { context }

This works 😅. I agree that this should be mentioned in the docs.
