### ISSUE TITLE
Why My Staline.nvim like this?

### ISSUE THREAD

**Issue by CSNinja11** [tamton-aquib/staline.nvim#24]
![Screenshot from 2022-01-19 16-47-31](https://user-images.githubusercontent.com/94297920/150128794-f9081d31-f8ba-4616-ae1b-dcd434014ec4.png)

I Use A .vim config but i use lua inside it so it's just this:
require('staline').setup {}

**Comment by tamton-aquib** [comment]
Heyyo @CSNinja11, that looks like a font issue to me 🤔 
Have you tried changing font for your terminal?

**Comment by bryant-the-coder** [comment]
i dont think it is staline problem tbh. It is the terminal font

**Comment by bryant-the-coder** [comment]
[jetbrains.zip](https://github.com/tamton-aquib/staline.nvim/files/7905319/jetbrains.zip)
try this

**Comment by CSNinja11** [comment]
> Heyyo @CSNinja11, that looks like a font issue to me thinking Have you tried changing font for your terminal?

It Didn't Work
I am giving Up
I Tried All Type Of Fonts

**Comment by bryant-the-coder** [comment]
yo hold up send me your config...

**Comment by bryant-the-coder** [comment]
dont give up

**Comment by CSNinja11** [comment]
ok man

**Comment by CSNinja11** [comment]
the font i use for the terminal is jetbrains.zip
distro is Garuda Linux

init.vim:
source $HOME/.config/nvim/vim-plug/plugins.vim


lua <<EOF
require('lualine').setup() 

EOF

plugins.vim:
" auto-install vim-plug
if empty(glob('~/.config/nvim/autoload/plug.vim'))
  silent !curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  "autocmd VimEnter * PlugInstall
  "autocmd VimEnter * PlugInstall | source $MYVIMRC
endif

call plug#begin('~/.config/nvim/autoload/plugged')

    " Better Syntax Support
    Plug 'sheerun/vim-polyglot'
    " File Explorer
    Plug 'scrooloose/NERDTree'
    " Auto pairs for '(' '[' '{'
    Plug 'jiangmiao/auto-pairs'
    " Status Line
    Plug 'nvim-lualine/lualine.nvim'
    Plug 'kyazdani42/nvim-web-devicons'




    call plug#end()


Note: I deleted staline.nvim

**Comment by CSNinja11** [comment]
i know it is a font problem but i tried lualine and it works!, but i really liked staline.nvim
but sorry man for wasting your time
i know i can't solve it

**Comment by bryant-the-coder** [comment]
i dont think it is staline's to be honest. It is either the fonts or the settings of your vimrc or the terminal. As what I have gathered from reddit and github, fonts and terminal ain't the problem. So i guess it might be the settings in your vimrc. I have been using jetbrans.zip for quite dome time now. It works fluently for your information. I will dig into your config when I have time because next week ks my exam loll. So i think you can reopen the issue

**Comment by tamton-aquib** [comment]
> i know it is a font problem but i tried lualine and it works!, but i really liked staline.nvim
but sorry man for wasting your time
i know i can't solve it

No problemo 😅 .  Lualine has all staline can offer + more. Hope u have a good time inside neovim 👍🏻

**Comment by CSNinja11** [comment]
i didn't have any hate with your app plugin man, i love your plugin but it didn't work for me :D
