### ISSUE TITLE
Consider adding highlight group support for the mode colors

### ISSUE THREAD

**Issue by DanisDGK** [tamton-aquib/staline.nvim#26]
I know specific sections already have highlight group support, but it would be very nice to be able to set mode colors to highlight groups as well.
This would make it possible to set the colors in an external theme, instead of having to manually change the colors in the `staline` configuration in case of a theme change.

Example:
```lua
require('staline').setup {
	mode_colors = {
		n = "StalineNormal",
		i = "StalineInsert",
	}
}
```

**Comment by tamton-aquib** [comment]
Heyyo @DanisDGK, sry for the late reply.

Ive thought about this approach before but didnt know why i abandoned it haha.
Will check and report back asap.

**Comment by tamton-aquib** [comment]
oops sorry for being late again haha 😅 

I guess it was mainly because of the light and simple design choice back then.
A single color for a single mode was the first thing i thought about, and extra highlights for extra colors.

But yes, in this case it will be hard for the colorscheme's to adapt.

**Comment by tamton-aquib** [comment]
Closing this issue for now, lemme know if you want to reopen 😅
