### ISSUE TITLE
Add Git Diff in StaLine

### ISSUE THREAD

**Issue by sahashirshendu** [tamton-aquib/staline.nvim#27]
Is it possible to add git diff in the statusline like lualine shows?

**Comment by bryant-the-coder** [comment]
i will try to implement this. =)

**Comment by tamton-aquib** [comment]
Heyyo @sahashirshendu ,

I have the gitsigns plugin installed and it exposes buffer variables like `gitsigns_status` and `gitsigns_status_dict`.
In my case, i use this component:
```lua
function()
    return vim.b.gitsigns_status or ''
end
```

This will be formatted the way that we provide inside gitsigns setup() function.

We could also use the `b:gitsigns_status_dict` for more finer control.

**Comment by sahashirshendu** [comment]
Thanks. It is what I was looking for.
