### ISSUE TITLE
TrueColor

### ISSUE THREAD

**Issue by Daniel794** [tamton-aquib/staline.nvim#28]
I liked the plugin very much and intalled staline on all of my desktops. In the terminals with truecolor support, it works fine, but I have a Ubuntu 14.04 laptop (needed for university purpose) and in that machine in gnome terminal, staline renders to be black n white (lualine worked fine there). Can something be done to remedy the situation?
![image](https://user-images.githubusercontent.com/59562163/160783940-65a70676-e2b6-4eed-b054-e3a7953aa634.png)

**Comment by tamton-aquib** [comment]
Heyyo @Daniel794,

One thing you could do is give highlight to each section components, and provide cterm values for those highlights. Example:

```lua
require ("staline").setup {
    sections = {
        left = {
            ' ',
            { 'StalineMode', 'mode' }
        },
        mid = {
            { 'StalineFileName', 'file_name' }
        }
    }
}

vim.cmd("highlight StalineFileName ctermfg=2")
vim.cmd("highlight StalineMode ctermfg=4")
```


Lualine uses a table for converting cterm colors to hex. And highlights in staline are a little different as said in #26  .
Its a limitation in staline due to the simple design 😅 .

**Comment by Daniel794** [comment]
> Its a limitation in staline due to the simple design

Thanks for the quick reply :) Btw, are you planning to add the support in near future?

**Comment by Daniel794** [comment]
> Its a limitation in staline due to the simple design  .

Thanks for the quick reply :) Btw, are you planning to add the support in near future?

**Comment by tamton-aquib** [comment]
> Btw, are you planning to add the support in near future?

it might need a little rewrite so probably later in the future 😬
