### ISSUE TITLE
Avoid using hardcoded colors

### ISSUE THREAD

**Issue by is0n** [tamton-aquib/staline.nvim#29]
The default `mode_colors` setting uses colors that don't work well with certain color schemes. I think that it would be better if `staline-nvim` would (by default) use colors based on the current color scheme instead of being hardcoded (kind of relates to #26).

I've gotten something like this to work with the following:
```lua
local function ExtractHl(name)
	return vim.api.nvim_exec('highlight ' .. name, true):match('guifg=(#[0-9A-Fa-f]+)')
end

require('staline').setup {
	mode_colors = {
		n  = ExtractHl("Normal"),
		i  = ExtractHl("Blue"),
		ic = ExtractHl("Green"),
		c  = ExtractHl("Purple"),
		v  = ExtractHl("Yellow"),
		['']  = ExtractHl("Yellow"),
		V  = ExtractHl("Orange"),
		t  = ExtractHl("Red"),
	}
}
```

This isn't perfect as `ExtractHl` will break if a highlight group does not `exist` or is `linked` to another group but it can definitely can be improved upon :D

**Comment by is0n** [comment]
`vim.api.nvim_get_hl_by_name(hl_name, true)` works great! This fixes the config from returning an error when a highlight group is `linked` but not when it does not `exist`. At that point however, I think it would make sense to `fallback` on the current `default` colors right?

**Comment by tamton-aquib** [comment]
Ah yes, setting fallback colors instead of hardcoding makes sense.
Will change when i get some free time 😅

**Comment by tamton-aquib** [comment]
Heyyo @is0n ,
I have pushed the fallback feature to main, let me know if it works when you have time.

**Comment by is0n** [comment]
It works perfectly and looks so nice!

Thanks again for your amazing work! 👍🏽
