### ISSUE TITLE
Works in VIM?

### ISSUE THREAD

**Issue by Mangeshrex** [tamton-aquib/staline.nvim#3]
does this statusline work in vim? i tried but it seems that it doesnt works with vim.

**Comment by tamton-aquib** [comment]
hey @Mangeshrex, sorry for the inconvenience.
This plugin was written in lua and will only work in neovim 0.5.0+ 

Here is a similar one written in vimscript: https://www.reddit.com/r/vim/comments/ld8h2j/i_made_a_status_line_from_scratch_no_plugins_used/

Actually that reddit post was what inspired me to make this plugin.

**Comment by Mangeshrex** [comment]
ahh no worries bro thanks for the reply and help :D
