### ISSUE TITLE
                                                                                                                                                                                                             E5108: Error executing lua ...vim/site/pack/packer/start/staline.nvim/lua/stabline.lua:52: module 'tables' not found:

### ISSUE THREAD

**Issue by T1m044325** [tamton-aquib/staline.nvim#30]
I was trying to install stabline with instructions from readme but encountered this error.

> E5108: Error executing lua ...vim/site/pack/packer/start/staline.nvim/lua/stabline.lua:52: module 'tables' not found:
        no field package.preload['tables']
        no file './tables.lua'
        no file '/home/timmy/neovim/.deps/usr/share/luajit-2.1.0-beta3/tables.lua'
        no file '/usr/local/share/lua/5.1/tables.lua'
        no file '/usr/local/share/lua/5.1/tables/init.lua'
        no file '/home/timmy/neovim/.deps/usr/share/lua/5.1/tables.lua'
        no file '/home/timmy/neovim/.deps/usr/share/lua/5.1/tables/init.lua'
        no file '/home/timmy/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/tables.lua'
        no file '/home/timmy/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/tables/init.lua'
        no file '/home/timmy/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/tables.lua'
        no file '/home/timmy/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/tables/init.lua'
        no file './tables.so'
        no file '/usr/local/lib/lua/5.1/tables.so'
        no file '/home/timmy/neovim/.deps/usr/lib/lua/5.1/tables.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/home/timmy/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/tables.so'
stack traceback:
        [C]: in function 'require'
        ...vim/site/pack/packer/start/staline.nvim/lua/stabline.lua:52: in function 'get_file_icon'
        ...vim/site/pack/packer/start/staline.nvim/lua/stabline.lua:80: in function <...vim/site/pack/packer/start/staline.nvim/lua/stabline.lua:66>

**Comment by tamton-aquib** [comment]
Oops, forgot to update the structure. Will do in a sec 😅

**Comment by tamton-aquib** [comment]
heyyo @T1m044325, lemme know if this fixes the issue

**Comment by T1m044325** [comment]
Thanks! Stabline works as smooth as a breeze now.
