### ISSUE TITLE
Cannot specify highlight group for user defined sections

### ISSUE THREAD

**Issue by xdeafbabe** [tamton-aquib/staline.nvim#36]
I have a custom section like following. I also tried returning only the path, so my middle group would be either like `mid = { { 'StalineFile', section_filename } }` or `mid = { section_filename }`.

```
local function section_filename()
    local dir = vim.fn.expand('%:p:h:t')
    local file = vim.fn.expand('%:t')
    local path = string.format('%s/%s', dir, file)
    if vim.bo.modifiable and vim.bo.modified then path = path .. '*' end
    if vim.bo.readonly then path = ' ' .. path end
    return { 'StalineFile', path }
end
```

However, in the first case I get this:
![image](https://user-images.githubusercontent.com/66640708/182428240-f2d25527-bb17-49e6-816d-59a044e6808d.png)

And in the second case this:
![image](https://user-images.githubusercontent.com/66640708/182428393-4b4591cc-5be9-4f39-b795-e4febb4a765c.png)

**Comment by tamton-aquib** [comment]
Heyyo @xdeafbabe , i havent set parse function to accept `highlight+function`  yet.
Will be implementing it shortly 😅

**Comment by tamton-aquib** [comment]
I have sent a fix, let me know if it works if you have time😅

**Comment by xdeafbabe** [comment]
@tamton-aquib It works just as I expected it to, thank you a lot!
