### ISSUE TITLE
Error starting any file

### ISSUE THREAD

**Issue by JjersaR** [tamton-aquib/staline.nvim#37]
I updated the plugins with Packer and since then staline no longer works.

![imagen](https://user-images.githubusercontent.com/86206596/184518677-b95c4500-506b-4199-998b-c3d8b751df7e.png)

This is my version of nvim
![imagen](https://user-images.githubusercontent.com/86206596/184518742-373e3f43-26e9-4c57-ac96-e9b164b404dd.png)

By executing this command :checkhealth all is well

**Comment by tamton-aquib** [comment]
Heyyo @JjersaR, can you send your staline config?

**Comment by JjersaR** [comment]
Yes, this is my configuration 
https://github.com/JjersaR/nvim/blob/main/lua/staline-config/init.lua

**Comment by tamton-aquib** [comment]
Each section can either be `{highlight, value}` or just be `value`.
On line 19 of your config, try changing:
```lua
'mode', {'StalineBranch', 'file_name', 'branch'},
```
to:
```lua
'mode', {'StalineBranch', 'file_name'}, { 'StalineBranch', 'branch'},
```

**Comment by JjersaR** [comment]
Thank you very much, it worked for me
