### ISSUE TITLE
Not an issue per say but is there a way to set the whole/partial path for the file name in the mid section?

### ISSUE THREAD

**Issue by MadoScientist97** [tamton-aquib/staline.nvim#38]
This becomes a problem if we are editing multiple files of the same name. Cant see the path under which the file is at a quick glance. 
Is there an option for that?

**Comment by tamton-aquib** [comment]
Heyyo @MadoScientist97 , are you looking for the `full_path` option inside setup.defaults?

**Comment by MadoScientist97** [comment]
Yeah I got that. But then I remembered why I turned it off. When the paths are too long the other sections gets pushed. I am now trying to modify the full path version so that you can specify a max char length (or maybe have a % based limit based on window size) after which it will start compressing the string ala starship prompt.

**Comment by tamton-aquib** [comment]
Ah right, i understand
Theres no conditional section rendering right now, but we could emulate it like:

```lua
require("staline").setup {
    sections = {
        mid = {
            { 'Staline', function()
                return vim.o.columns <= 60 and '%f' or '%F'
            end }
        },
     }
}
```

But in this case, we lose the icon, and will have to manually add it.

Or the inner parsing function can be improved a bit to check if the return value of the function is one of the predefined section 😅

**Comment by MadoScientist97** [comment]
If I do make it similar to starship I'll do a pull request, you can decide if you want to add it. When I'll get to it though, I can't say. 😅

**Comment by tamton-aquib** [comment]
I dont know how your starship displays path , but if your sending a PR, make sure to do it in dev branch btw 😅

**Comment by tamton-aquib** [comment]
Closing the issue due to inactivity. Feel free to open if the problem persists. 👍🏻
