### ISSUE TITLE
termguicolors requirement is not mentioned anywhere

### ISSUE THREAD

**Issue by EPSILON0-dev** [tamton-aquib/staline.nvim#39]
I tried to set up staline and kept having a problem that no colors would appear, it would just be white text on transparent background. After some time I discovered that termguicolors has to be set, it probably should have been obvious but it wasn't to me.

It's not mentioned neither in README nor in wiki, it would be nice if it was somewhere in README so no one has the same problem.

**Comment by tamton-aquib** [comment]
Heyyo @EPSILON0-dev, thanks for pointing that out 😅 .
I have added it to the requirements section in readme.

**Comment by EPSILON0-dev** [comment]
Thanks, that will save some time for the next person that has this problem.
