### ISSUE TITLE
can we add custom statusline module.

### ISSUE THREAD

**Issue by blackCauldron7** [tamton-aquib/staline.nvim#4]
I wanted to add nvim_lsp diagnostics and treesitter nearest function to my staline.

**Comment by tamton-aquib** [comment]
Hey @blackCauldron7 , sorry for the inconvenience and late reply.😅

As it states in README, staline doesn't have git or lsp related stuff by default but,
defaults.filename_section and defaults.cool_symbol can take custom modules.

The easiest way would be to create a function which returns a string and pass it to filename_section or cool_symbol.
For example,

```lua
function Get_lsp_stuff()
    local errors = vim.lsp.diagnostic.get_count(0, 'Error')
    return " "..errors
end
```
and pass that function into filename_section,
```lua
require'staline'.setup{
    defaults = {
        filename_section = '%{luaeval("Get_lsp_stuff()")}'
    }
}
```

Which would look something like,

![image](https://user-images.githubusercontent.com/77913442/124610190-e9d90100-de8d-11eb-8064-5aa689b8de63.png)

**Comment by blackCauldron7** [comment]
thanks that works.

Thanks for the Amazing Plugin.
