### ISSUE TITLE
Not working with init.vim

### ISSUE THREAD

**Issue by Stefanomarton** [tamton-aquib/staline.nvim#40]
Hi there, 
first of all very nice work, i really like the look of the bar.
I'm trying to setup it with init.vim as I'm not lua master. I've set all the requirements in my config
```
set termguicolors
set laststatus=3
set showtabline=2
```
I've inserted the default config in an external .lua file 
```
luafile ~/.config/nvim/lua/staline.lua
```
nvim load with no errors but the bar does not appear. Can you spot anything wrong?
I'm having no problem doing the same with nvimtree
Thanks for your time
~Ste

**Comment by tamton-aquib** [comment]
Heyyo @Stefanomarton, sorry for the late reply 😅 

What version of nvim are you on?
how does your config structure look like?
Are you calling `luafile path` inside init.vim?

Also, could you try setting this line inside init.vim (after installing the plugin without the `luafile path`)
```vim
lua require("staline").setup()
```

**Comment by Stefanomarton** [comment]
So 
I have version 0.7.2
This is my file structure 
![image](https://user-images.githubusercontent.com/80684231/186892325-364cbb71-a7e1-4803-96c1-df32c62473f0.png)
I tried using 
`lua require("staline").setup()`
But i get this
![image](https://user-images.githubusercontent.com/80684231/186894339-a3081a62-5c0a-4bc5-8617-5974e07318c2.png)

**Comment by tamton-aquib** [comment]
That looks like a name collision.

Set this line in `init.vim`:
```vim
lua require("staline").setup()
```
remove all other things related to staline (including the lua/staline.lua file which causes the collision)




So in short, the only two lines you have related to staline will be
```vim
Plug 'tamton-aquib/staline.nvim'
```
and
```vim
lua require("staline").setup()
```

**Comment by Stefanomarton** [comment]
Ok now works
I can't get why I can't include in an external file :/
I have to insert my bar config in init.vim?

**Comment by tamton-aquib** [comment]
name the file other than `staline.lua` to avoid name collisions and we're good to go 😅 

Also you can
```vim
lua require("staline-config")
```
instead of
```vim
luafile ~/.config/nvim/lua/staline-config.lua
```
where `staline-config.lua` is the new filename (`~/.config/nvim/lua/staline-config.lua`)

**Comment by Stefanomarton** [comment]
THANKS A LOT
