### ISSUE TITLE
Staline seems to conflict with lsp hover

### ISSUE THREAD

**Issue by rychardvale** [tamton-aquib/staline.nvim#41]
Hey all!

I'm trying to setup staline but for some reason it seems to conflict with lsp window popup. When I try to run `vim.lsp.buf.hover() ` nothing happens, only when run it again then the popup appears but then it jumps to the floating window.

Any idea what is going on?

**Comment by tamton-aquib** [comment]
Heyyo @rychardvale 

heres what docs for hover() say:
![image](https://user-images.githubusercontent.com/77913442/189039339-11377f3e-106b-4f47-a401-02f796f7f77c.png)
i think its intended.

If you want to turn it off:
```lua
vim.lsp.handlers["textDocument/hover"] =  vim.lsp.with( vim.lsp.handlers.hover, {border = border})
```

**Comment by rychardvale** [comment]
You can see it flashing only sometimes due to recording being 60hz.

https://user-images.githubusercontent.com/54805553/189159378-9cef7bb9-df85-4ba5-98d4-eeab25a12950.mp4

I tries to check for conflicting remaps but couldn't find any, and it would be weird since staline doesn't map any key.

**Comment by tamton-aquib** [comment]
Are you sure the problem is from staline? 😅 

Also is your neovim config on git?

**Comment by rychardvale** [comment]
[Now it is](https://github.com/rychardvale/.config/tree/main/nvim)

I must be doing something wrong :face_exhaling:

**Comment by rychardvale** [comment]
Yeah man, no worries, I don't know what is wrong but I'll keep tweaking things around to see if I spot the bug. 
Thanks!

**Comment by rychardvale** [comment]
Hey! Managed to get it to work a few days ago, apparently the bug happens when I load staline after setting up my colorscheme... So there's that!

**Comment by tamton-aquib** [comment]
Heyyo @rychardvale tysm, i tried bisecting your config but couldn't find anything weird. 😅 
Thank you again.
