### ISSUE TITLE
Lsp_name

### ISSUE THREAD

**Issue by Pakrohk** [tamton-aquib/staline.nvim#43]
Please pay attention to the link I am sending.
https://github.com/Pakrohk-DotFiles/NvPak/issues/45
We have been trying to solve this problem for some time.
But the problem is not from lsp, even if the lsp server is disabled manually, there is still a problem, and this can be caused by the method of calling servers in staline.

**Comment by tamton-aquib** [comment]
I know its a little late but, has the issue been resolved? 😅

**Comment by Pakrohk** [comment]
> I know its a little late but, has the issue been resolved? sweat_smile

nah, unfortunately I had to migrate to lualine.

**Comment by tamton-aquib** [comment]
> nah, unfortunately I had to migrate to lualine.

cool, Im closing the issue for now.
Feel free to open whenever necessary.
