### ISSUE TITLE
Lazy Plugin Manager

### ISSUE THREAD

**Issue by Pakrohk** [tamton-aquib/staline.nvim#44]
To learn how to use [Lazy.nvim](https://github.com/folke/lazy.nvim) to install StaLine and STabline, you can use the following method that we took in [NvPak](https://github.com/Pakrohk-DotFiles/NvPak) :

```lua
-- StaLine Neovim StatusLine
	{
		"tamton-aquib/staline.nvim",
		event = { "BufReadPre", "BufNew" },
		dependencies = "nvim-tree/nvim-web-devicons",
		config = function()
			....
			....
		end,
	},
```

**Comment by tamton-aquib** [comment]
is this related to #43 ?
if yes, could you please close this issue
