### ISSUE TITLE
Git diff in statusbar

### ISSUE THREAD

**Issue by abhilash26** [tamton-aquib/staline.nvim#49]
First of all thank you for making this plugin.

I wanted to add git diff in my statusbar. I have seen #27 and used that to make up some code

```
      local git_status = function(type, prefix)
        local status = vim.b.gitsigns_status_dict
        if not status then
          return nil
        end
        if not status[type] or status[type] == 0 then
          return nil
        end
        return prefix .. status[type]
      end
```
      
     In the statusline 
      
 ```
            {
              "GitSignsAdd",
              function()
                return git_status("added", " ") or ''
              end
            },
            " ",
            {
              "GitSignsChange",
              function()
                return git_status("changed", " ") or ''
              end
            },
            " ",
            {
              "GitSignsDelete",
              function()
                return git_status("removed", " ") or ''
              end
            }

            
 ```   
            
            
![image](https://github.com/tamton-aquib/staline.nvim/assets/28080925/66a027be-400b-4b41-ad0d-4f10d68a75a2)

            
          I couldnot do this in one block as I needed different highlights for each type of diff.
          Is there any way to do this better?  Also, can you add this as a module as it is not a specific requirement.

**Comment by tamton-aquib** [comment]
Heyyo @abhilash26,

The problem with git related info in statuslines is, it becomes sluggish if not done correctly. 
Even the git branch section is inefficient in staline.

I am thinking of providing integrations with gitsigns like you mentioned. Feline did something similar too.
But it might take some time because I have exams 😭

**Comment by abhilash26** [comment]
@tamton-aquib, 
Salaam Alekum,
Good luck  in your exams. I did not know you are young. Please let this issue opened.

**Comment by tamton-aquib** [comment]
> Please let this issue opened.

Sure 👍🏻

**Comment by tamton-aquib** [comment]
Hi @abhilash26,

So I have been checking issues and PR's in all my repos and wanted to check this one too. I researched a bit and gitsigns already have statusline related config defined.

Especially `:h gitsigns-config-status_formatter`.

After defining it, we could just add the `git_diff` section to staline.

**Comment by tamton-aquib** [comment]
Closing this issue for now but feel free to open it if needed 👍🏻

**Comment by abhilash26** [comment]
Hello @tamton-aquib,

I tried using `git_diff` but couldn't get the icons and colors, all of them were in one color.
I have a request, please use git_diff and give us options for icons and color for each (added, modified and deleted) highlights.

**Comment by abhilash26** [comment]
Nevermind, I rolled my own statusline plugin 
https://github.com/abhilash26/zenline.nvim
