### ISSUE TITLE
If added lsp and treesitter

### ISSUE THREAD

**Issue by ashincoder** [tamton-aquib/staline.nvim#5]
Hello I love the plugins of it's minimalism. If the lsp and treesitter things are added will add it to [StarVim](https://github.com/ashincoder/StarVim)

**Comment by tamton-aquib** [comment]
Heyyo @ashincoder, sorry for the inconvenience and late reply 😅 ,

As said in the `cons` section of readme, this statusline doesn't come with lsp stuff by default.
But `defaults.cool_symbol` and `defaults.filename_section` can take custom modules. An easy way would be to define a function which returns a string, and pass it to the above said sections.

For Example,
```lua
function Lsp_stuff()
    local get = vim.lsp.diagnostic.get_count
    local signs =
    "  "..get(0, 'Error')..
    "  "..get(0, 'Warning')..
    "  "..get(0, 'Information')..
    " " ..get(0, 'Hint')

    return signs
end
```

And then pass it to, say `defaults.filename_section`
```lua
require'staline'.setup{
    defaults = {
        filename_section = "%{luaeval('Lsp_stuff()')}"
    }
}
```

Which would look something like:

![example_lsp](https://i.imgur.com/uVP51Bo.png)

**Comment by ashincoder** [comment]
Yeah thanks.

**Comment by ashincoder** [comment]
It would be great if those were added. Right

**Comment by tamton-aquib** [comment]
You mean add inside the plugin?

**Comment by ashincoder** [comment]
Yeah

**Comment by tamton-aquib** [comment]
Oh, I think leaving this to the user would be better 😅.

Maybe I'll add this in beta branch.

**Comment by ashincoder** [comment]
yeah great
