### ISSUE TITLE
Is there a way to disable staline in Neotree?

### ISSUE THREAD

**Issue by shebangcode** [tamton-aquib/staline.nvim#51]
Hi, I'm trying to setup staline to not show on a Neotree window. Is it possible to do this? If so, how?

**Comment by tamton-aquib** [comment]
Heyyo @shebangcode,

Are you using a global statusline? (`:h laststatus`)

If yes, you might have to redefine the left section. Something like(not tested):

```lua
-- From issue #50 
require("staline").setup {
	sections = {
		left = {
			function()
	          if #vim.tbl_filter(function(b) return vim.bo[b].ft == "neo-tree" end, vim.api.nvim_list_bufs()) > 0 then
	            return (" "):rep(require("neo-tree").config.window.width)
			  else
				return ""
	          end
	        end,
			-- Rest of the section
		}
	}
}
```

**Comment by shebangcode** [comment]
I have already tried to do so, in this screenshot:
![Screenshot 2023-06-26 17 22 46](https://github.com/tamton-aquib/staline.nvim/assets/94982718/a28ddf66-cbcc-409a-8e04-46160bd3718c)
The line still shows up. I'm sorry for bothering you man.

**Comment by tamton-aquib** [comment]
That should basically show an error. 
The alternate way to specify the key would be to:

```lua
special_table = {
	["neo-tree"] = {"NeoTree", "some_icon" },
	-- ... rest of the table
}
```


> I'm sorry for bothering you man.

Haha, no problemo!

**Comment by shebangcode** [comment]
Do I need to put an Icon, or just put a space?

**Comment by shebangcode** [comment]
Nevermind, it works. Thanks!
