### ISSUE TITLE
Can I change the mode icons for Visual-line and Visual-block?

### ISSUE THREAD

**Issue by shebangcode** [tamton-aquib/staline.nvim#52]
Hello, I'm trying to change the mode icons for Visual-line and block (because the icons used are no longer availiable and are replaced by what I think are arabic characters), but I can't find a way to do so. Is it possible to change these icons?

**Comment by tamton-aquib** [comment]
Heyyo @shebangcode, 
it is possible via the `mode_icons` option inside the setup as mentioned in the README.

Example:

```lua
require("staline").setup {
	mode_icons = {
		["v"] = "some icon", -- visual mode
		["V"] = "some icon", -- visual line mode
        [""] = "some icon" -- visual block mode
	},
    --- rest of the setup
}

```

Notice that visual-block needs the string literally as such. This was acheived by `<C-v><C-v>`.
The first `<C-v>` for keystroke input and second `<C-v>` is the visual block keybind
